### ISSUE TITLE
ESP directory?

### ISSUE THREAD

**Issue by 6etacat** [AnarchyLinux/installer#212]
I did a clean install on UEFI yesterday and found that grub is not installed correctly. I had to arch-chroot into the system to re-install grub(using the arch wiki's instructions) to get it working. I read arch-installer.sh and found that the UEFI esp directory seems to be wrong. We are using /boot rather than /boot/efi. Also, I believe adding /boot/efi in the mount points would also be a good idea. From my knowledge, Arch won't boot in UEFI if we do not have an esp partition mounted as /boot/efi.

**Comment by tydlwav** [comment]
If this is an issue, I'd try to fix the bug and add a pull request.

**Comment by condor2** [comment]
You used 2.2.6?

**Comment by deadhead420** [comment]
Looking into it now. Its possible to have the esp anywhere. /boot or /boot/efi. Actually its generally recommended to have the esp at /boot because systemd-boot and syslinux both require to kernel and initramfs to be under the root of the esp (meaning if you make the esp /boot/efi the kernel is stored at /boot so needs to be copied to /boot/efi in order to boot with systemd or syslinux, the same is not true for grub). Actually when using auto partition with uefi the esp is set to /boot. This seems to only be a bug in manual partitioning? Anyway looking into it now...

**Comment by deadhead420** [comment]
Just tested with manual partitioning. I mounted the esp at /boot, used grub as my bootloader, system booted just fine.... Testing now with the esp mounted at /boot/efi

**Comment by deadhead420** [comment]
Installed again with UEFI + grub. Manual partitioning, this time I used /boot/efi as the esp. System booted just fine... Could you provide more info on your install method? What installer version did you use? What kernel did you select (Standard, grsec, or lts)?

**Comment by deadhead420** [comment]
Also tested manual partitioning + UEFI with both syslinux and systemd-boot with the esp at /boot. Both worked perfect... Now going to test on real hardware

**Comment by tydlwav** [comment]
I see that using mounting the efi partition to /boot would work if you have a clean install, but multibooting with other linux distributions or with windows would not end up well. Also, reference [this](https://wiki.archlinux.org/index.php/Talk:EFISTUB#ESP_mount_points).
