### ISSUE TITLE
Not booting on 32-bit EFI systems

### ISSUE THREAD

**Issue by ngustavo** [AnarchyLinux/installer#538]
Hi, I hope someone can help me.
I'm trying to install Arch on a 32-bit EFI system with 64-bit Intel Atom. These are called 'Bay Trail' tablets/PCs. I actually managed to install Arch with this script:
https://github.com/emerinohdz/arch64-efi32
Is there a way to generate a custom Anywhere ISO with 32-bit EFI baked in?
Thank you.

**Comment by Translator5** [comment]
I try 17-times to install Anarchy-Arch on my 64bit GPT 2 TB hard-drive where my old data is stored in a own partition...
I tried as well as Syslinux as well as Grub2 installations.. 
No one loader starts, no grub-console & syslinux talks about false hard-drive...

While Linux Mint and Debian does work fine.

Also I installed Anarchy on a 250GB hard drive what works great as well - what could be the reason that a installation on a specific hard drive do not work :/

A pure clear arch installation do not work as well for this HD.

**Comment by nastybuttler322** [comment]
@Translator5 Get into your system BIOS, before your operating system boots, and select the drive with Arch to boot.

If that does not work, install it with out UEFI, and no GPT. I set a timer of 10 seconds in my BIOS to allow me enough time to select which drive I want to boot from, because I also run Windows 10 with fastboot enabled. So I don't use the OS prober. 

I recommend Syslinux. I just like it better. It has the Anarchy splash screen for the boot.

**Comment by Translator5** [comment]
Problem is fixed, my motherboard just do not support UEFI 😆 ... Simply installed Grup on a partition now - all works fine!

**Comment by erazemkokot** [comment]
Closed since we don't support 32-bit systems.

**Comment by mirh** [comment]
For the n-th time, 32-bit **EFI** isn't the same of a 32-bit ***CPU***.

**Comment by erazemkokot** [comment]
Thanks for clarifying @mirh, will update the comment. I'll still leave it closed since the original author of the issue hasn't replied and from what I can gather from the comments it's more of a hardware problem (since it happens with pure Arch too, and mostly on specific hard drives?).

**Comment by mirh** [comment]
Not here. In the sense that just about every feature request about this, always end up with the same anthem. 
[This](https://bugs.archlinux.org/task/53182) was the bug report upstream that was just closed randomly (syslinux being dead perhaps being a reason). 

The hard disk also isn't meaningful at all. It was probably booting with CSM enabled in bios mode.

**Comment by erazemkokot** [comment]
Hmm, ok, thanks for clarifying again.

**Comment by ngustavo** [comment]
I haven't replied because I installed Arch manually and discovered that other things wouldn't work since it's a cheap Windows tablet.
Got Windows back on it. Haven't used that thing since.
But thanks for your support, guys.

**Comment by erazemkokot** [comment]
Thanks for checking Anarchy out, sorry we couldn't help fix the problem.

**Comment by mirh** [comment]
> and discovered that other things wouldn't work since it's a cheap Windows tablet.

Everything else has been fixed by now. [Hibernation](https://www.phoronix.com/scan.php?page=news_item&px=Baytrail-Cherrytrail-Hibernate), [audio](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1563110),  even the [infamous](https://bugzilla.kernel.org/show_bug.cgi?id=109051) "low power hanging bug" is just a memory. 
But whatever I guess.
