### ISSUE TITLE
Anarchy Repository

### ISSUE THREAD

**Issue by JackNapier151** [AnarchyLinux/installer#892]
## Description

Create a repository (PKGBUILD and * .pkg.tar.xz) with Anarchy settings (zshrc, Desktop Enviroment, ...) such as walpapers, app to instalation, ... etc. Here on GitHub, to be able to use it at any time.

**Comment by PandaFoss** [comment]
The wallpapers can be found in the [brands](https://github.com/AnarchyLinux/brand) repository. 
Although it is not a separate repository, customizations of the shell and desktop environments can be found in the [extra](https://github.com/AnarchyLinux/installer/tree/master/extra) folder within this repo... :)

**Comment by erazemkokot** [comment]
@JackNapier15 package repos are much more annoying to maintain than just simple files (e.g. if we want users to be able to update the files with `anarchy -u`, we have to host the repository somewhere, instead of just changing the files in the main Github repo), so we believe our current configuration is fairly good (although our opinion might change in the future).

To clarify: Anarchy is not a distro or trying to be one, is is an installer for Arch, so we want to make it as simple and maintenance free as we can.
