### ISSUE TITLE
Ignored FAT label limit, typos, selecting conflicting options possible, and "please report to developer"

### ISSUE THREAD

**Issue by tech-tie** [AnarchyLinux/installer#959]
## Basic info:

**Anarchy version**:  1.0.10

**Installation method (VM/Host)**:  Host

**System specifications (Processor, GPU, RAM ...)**:
CPU:  AMD Ryzen 7 1800X
GPU:  AMD Radeon R7 200 Series (possibly a 260X)
RAM:  16 GB
Primary SSD:  ~120 GB
Screen:  5:4 @ 75 Hz via HDMI (DVI-D)

## What you expected would happen

1. The USB actually booting without having to edit the "archiso-x86_64.conf" to adhere to the 11 character label limit of FAT.
2. There not being typos in the German translation.
3. Selecting conflicting options being impossible.
4. The installer actually working.

## What actually happened

1. I had to edit the "archiso-x86_64.conf" to make the expected medium name compliant with the FAT label character limit.
2. There were typos in the German translation.
3. Selecting conflicting options is possible
4. The installer told me to report an "unexpected error" of some kind.

## Steps needed to reproduce the bug

1.1. Download the ISO.
1.2. Try to flash it onto a USB formatted with FAT.

2.1. Launch the Anarchy installer.
2.2. Select German.

3.1. Select libreoffice-fresh and libreoffice-stable.

4.1. Launch the Anarchy installer.
4.2. Try to install Arch.

## Extra info

Anarchy.log:
```
This was too long to paste, so see the attached file:
[anarchy.log](https://github.com/AnarchyLinux/installer/files/4205150/anarchy.log)
```

## Possible fixes

1. Just remove the "V" from "ANARCHYV1010".
2. Run the translations thru spellcheck.
3. Make the selection of conflicting options impossible. Or warn the user about it instead of forcing them to redo the entire setup after pacman inevitably fails.

## Bug report checklist

* [x] I've read the [Reporting Issues Wiki Page](https://github.com/AnarchyLinux/installer/wiki/Reporting-issues)
* [x] I've removed unnecessary sections of the bug submission template
* [x] I understand that if I don't do everything listed in the checkmarks above my issue won't be considered a priority and may get closed at any time without warning, because I didn't take the time to properly submit my bug report

**Comment by erazemkokot** [comment]
Hi, I'll fix the FAT character limit, but there isn't anything I can do with the German translation. These are submitted by the users, since we (the devs) don't speak every language. The only true way to make the installer typo-free would be to remove translations alltogether and just use English, but we think it's better to not go that route.

You're free to run the translations through the spellchecker yourself though, and we'd appreciate it.

Regarding the conflicting options, this is being reworked on the pacman-fix branch and will hopefully be fully integrated soon. Can you describe the conflicting options though? I get the pacman failing (that's what will be fixed in pacman-fix), but I don't know what conflicting options you're talking about.

Regarding no. 4, did you try updating Anarchy and pacman's keys using `anarchy -u` and `anarchy -k`?

**Comment by tech-tie** [comment]
Thank you! Sorry for having been so unpleasant.

Okay, I can try find the exact misspellings and fix them.

Yes, I did try update it. I tried just selecting less packages to install and it suddenly worked, but only sometimes. The resulting encrypted drive sadly wouldn't boot after the install, so I'll try again without the encryption.
